-- Defines item/tool metadata incl. footprint size

CREATE TABLE IF NOT EXISTS game_item_details (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tool VARCHAR(100) NOT NULL,
  display_name VARCHAR(191) NULL,
  category VARCHAR(50) NOT NULL DEFAULT 'general',
  footprint_width INT UNSIGNED NOT NULL DEFAULT 1,
  footprint_height INT UNSIGNED NOT NULL DEFAULT 1,
  build_cost INT UNSIGNED NULL,
  build_time_seconds INT UNSIGNED NULL,
  requires_power TINYINT(1) NOT NULL DEFAULT 0,
  requires_water TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_game_item_details_tool (tool),
  KEY idx_game_item_details_category (category, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO game_item_details (tool, display_name, category, footprint_width, footprint_height, is_active)
VALUES
  ('power_plant', 'Power Plant', 'infrastructure', 2, 2, 1),
  ('water_tower', 'Water Tower', 'infrastructure', 1, 1, 1),
  ('hospital', 'Hospital', 'service', 2, 2, 1),
  ('school', 'School', 'service', 2, 2, 1),
  ('stadium', 'Stadium', 'service', 3, 3, 1),
  ('museum', 'Museum', 'service', 3, 3, 1),
  ('university', 'University', 'service', 3, 3, 1),
  ('airport', 'Airport', 'infrastructure', 4, 4, 1),
  ('space_program', 'Space Program', 'service', 3, 3, 1),
  ('park_large', 'Large Park', 'decoration', 3, 3, 1),
  ('mansion', 'Mansion', 'residential', 2, 2, 1),
  ('apartment_low', 'Apartment Low', 'residential', 2, 2, 1),
  ('apartment_high', 'Apartment High', 'residential', 2, 2, 1),
  ('office_low', 'Office Low', 'commercial', 2, 2, 1),
  ('office_high', 'Office High', 'commercial', 2, 2, 1),
  ('mall', 'Mall', 'commercial', 3, 3, 1),
  ('factory_medium', 'Factory Medium', 'industrial', 2, 2, 1),
  ('factory_large', 'Factory Large', 'industrial', 3, 3, 1),
  ('warehouse', 'Warehouse', 'industrial', 2, 2, 1),
  ('city_hall', 'City Hall', 'service', 2, 2, 1),
  ('amusement_park', 'Amusement Park', 'decoration', 4, 4, 1),
  ('playground_large', 'Playground Large', 'decoration', 2, 2, 1),
  ('baseball_field_small', 'Baseball Field', 'decoration', 2, 2, 1),
  ('football_field', 'Football Field', 'decoration', 2, 2, 1),
  ('baseball_stadium', 'Baseball Stadium', 'decoration', 3, 3, 1),
  ('mini_golf_course', 'Mini Golf', 'decoration', 2, 2, 1),
  ('go_kart_track', 'Go Kart', 'decoration', 2, 2, 1),
  ('amphitheater', 'Amphitheater', 'decoration', 2, 2, 1),
  ('greenhouse_garden', 'Greenhouse', 'decoration', 2, 2, 1),
  ('marina_docks_small', 'Marina Docks', 'decoration', 2, 2, 1),
  ('roller_coaster_small', 'Roller Coaster', 'decoration', 2, 2, 1),
  ('mountain_lodge', 'Mountain Lodge', 'decoration', 2, 2, 1),
  ('mountain_trailhead', 'Trailhead', 'decoration', 3, 3, 1),
  ('rail_station', 'Rail Station', 'infrastructure', 2, 2, 1),
  ('military_base', 'Military Base', 'service', 3, 3, 1),
  ('military_barracks', 'Military Barracks', 'service', 2, 2, 1)
ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  category = VALUES(category),
  footprint_width = VALUES(footprint_width),
  footprint_height = VALUES(footprint_height),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;
