-- Ensure all placeable tools have SQL price metadata.
-- Server-side money checks for placements read game_item_details.build_cost.

UPDATE game_item_details
SET build_cost = 0
WHERE build_cost IS NULL;

ALTER TABLE game_item_details
  MODIFY COLUMN build_cost INT UNSIGNED NOT NULL DEFAULT 0;

INSERT INTO game_item_details (tool, display_name, category, footprint_width, footprint_height, build_cost, is_active)
VALUES
  ('road', 'Road', 'infrastructure', 1, 1, 25, 1),
  ('rail', 'Rail', 'infrastructure', 1, 1, 40, 1),
  ('subway', 'Subway', 'infrastructure', 1, 1, 50, 1),
  ('expand_city', 'Expand City', 'city_management', 1, 1, 50000, 1),
  ('shrink_city', 'Shrink City', 'city_management', 1, 1, 0, 0),
  ('tree', 'Tree', 'decoration', 1, 1, 15, 1),
  ('tree_oak', 'Eiche', 'decoration', 1, 1, 20, 1),
  ('tree_maple', 'Ahorn', 'decoration', 1, 1, 20, 1),
  ('tree_birch', 'Birke', 'decoration', 1, 1, 20, 1),
  ('tree_willow', 'Weide', 'decoration', 1, 1, 25, 1),
  ('tree_pine', 'Kiefer', 'decoration', 1, 1, 20, 1),
  ('tree_spruce', 'Fichte', 'decoration', 1, 1, 20, 1),
  ('tree_fir', 'Tanne', 'decoration', 1, 1, 20, 1),
  ('tree_cedar', 'Zeder', 'decoration', 1, 1, 25, 1),
  ('tree_palm', 'Palme', 'decoration', 1, 1, 25, 1),
  ('tree_bamboo', 'Bambus', 'decoration', 1, 1, 20, 1),
  ('tree_coconut', 'Kokospalme', 'decoration', 1, 1, 25, 1),
  ('tree_cherry', 'Kirschbaum', 'decoration', 1, 1, 30, 1),
  ('tree_magnolia', 'Magnolie', 'decoration', 1, 1, 30, 1),
  ('tree_jacaranda', 'Jakaranda', 'decoration', 1, 1, 30, 1),
  ('tree_wisteria', 'Glyzinie', 'decoration', 1, 1, 30, 1),
  ('bush_hedge', 'Hecke', 'decoration', 1, 1, 15, 1),
  ('bush_flowering', 'Bluetenbusch', 'decoration', 1, 1, 15, 1),
  ('topiary_ball', 'Buchsbaum-Kugel', 'decoration', 1, 1, 30, 1),
  ('topiary_spiral', 'Buchsbaum-Spirale', 'decoration', 1, 1, 35, 1),
  ('flower_bed', 'Blumenbeet', 'decoration', 1, 1, 20, 1),
  ('flower_planter', 'Blumenkuebel', 'decoration', 1, 1, 20, 1),
  ('police_station', 'Police', 'service', 1, 1, 500, 1),
  ('fire_station', 'Fire Station', 'service', 1, 1, 500, 1),
  ('water_tower', 'Water Tower', 'infrastructure', 1, 1, 1000, 1),
  ('subway_station', 'Subway Station', 'infrastructure', 1, 1, 750, 1),
  ('park', 'Small Park', 'decoration', 1, 1, 150, 1),
  ('tennis', 'Tennis Court', 'decoration', 1, 1, 200, 1),
  ('basketball_courts', 'Basketball Courts', 'decoration', 1, 1, 250, 1),
  ('playground_small', 'Small Playground', 'decoration', 1, 1, 200, 1),
  ('playground_large', 'Large Playground', 'decoration', 2, 2, 350, 1),
  ('soccer_field_small', 'Soccer Field', 'decoration', 1, 1, 400, 1),
  ('community_center', 'Community Center', 'service', 1, 1, 500, 1),
  ('office_building_small', 'Small Office', 'commercial', 1, 1, 600, 1),
  ('swimming_pool', 'Swimming Pool', 'decoration', 1, 1, 450, 1),
  ('skate_park', 'Skate Park', 'decoration', 1, 1, 300, 1),
  ('bleachers_field', 'Bleachers Field', 'decoration', 1, 1, 350, 1),
  ('animal_pens_farm', 'Animal Pens', 'decoration', 1, 1, 400, 1),
  ('cabin_house', 'Cabin House', 'decoration', 1, 1, 300, 1),
  ('campground', 'Campground', 'decoration', 1, 1, 250, 1),
  ('pier_large', 'Pier', 'decoration', 1, 1, 600, 1),
  ('community_garden', 'Community Garden', 'decoration', 1, 1, 200, 1),
  ('pond_park', 'Pond Park', 'decoration', 1, 1, 350, 1),
  ('park_gate', 'Park Gate', 'decoration', 1, 1, 150, 1),
  ('terrain_raise', 'Terrain Raise', 'terrain', 1, 1, 50, 1),
  ('terrain_lower', 'Terrain Lower', 'terrain', 1, 1, 50, 1),
  ('terrain_lower2', 'Terrain Lower 2', 'terrain', 1, 1, 90, 1),
  ('terrain_hill', 'Terrain Hill', 'terrain', 1, 1, 200, 1),
  ('terrain_mountain', 'Terrain Mountain', 'terrain', 1, 1, 500, 1),
  ('terrain_flatten', 'Terrain Flatten', 'terrain', 1, 1, 100, 1),
  ('paint_green', 'Paint Green', 'terrain', 1, 1, 10, 1),
  ('paint_sand', 'Paint Sand', 'terrain', 1, 1, 10, 1),
  ('paint_dirt', 'Paint Dirt', 'terrain', 1, 1, 10, 1),
  ('paint_snow', 'Paint Snow', 'terrain', 1, 1, 10, 1),
  ('paint_dark_grass', 'Paint Dark Grass', 'terrain', 1, 1, 10, 1),
  ('paint_rock', 'Paint Rock', 'terrain', 1, 1, 10, 1),
  ('paint_reset', 'Paint Reset', 'terrain', 1, 1, 0, 1),
  ('hospital', 'Hospital', 'service', 2, 2, 1000, 1),
  ('school', 'School', 'service', 2, 2, 400, 1),
  ('university', 'University', 'service', 3, 3, 2000, 1),
  ('power_plant', 'Power Plant', 'infrastructure', 2, 2, 3000, 1),
  ('rail_station', 'Rail Station', 'infrastructure', 2, 2, 1000, 1),
  ('stadium', 'Stadium', 'service', 3, 3, 5000, 1),
  ('museum', 'Museum', 'service', 3, 3, 4000, 1),
  ('airport', 'Airport', 'infrastructure', 4, 4, 10000, 1),
  ('space_program', 'Space Program', 'service', 3, 3, 15000, 1),
  ('city_hall', 'City Hall', 'service', 2, 2, 6000, 1),
  ('amusement_park', 'Amusement Park', 'decoration', 4, 4, 12000, 1),
  ('park_large', 'Large Park', 'decoration', 3, 3, 600, 1),
  ('mansion', 'Mansion', 'residential', 2, 2, 800, 1),
  ('apartment_low', 'Apartment Low', 'residential', 2, 2, 1200, 1),
  ('apartment_high', 'Apartment High', 'residential', 2, 2, 2400, 1),
  ('office_low', 'Office Low', 'commercial', 2, 2, 1800, 1),
  ('office_high', 'Office High', 'commercial', 2, 2, 3600, 1),
  ('mall', 'Mall', 'commercial', 3, 3, 5500, 1),
  ('factory_medium', 'Factory Medium', 'industrial', 2, 2, 2000, 1),
  ('factory_large', 'Factory Large', 'industrial', 3, 3, 4500, 1),
  ('warehouse', 'Warehouse', 'industrial', 2, 2, 1600, 1),
  ('baseball_field_small', 'Baseball Field', 'decoration', 2, 2, 800, 1),
  ('football_field', 'Football Field', 'decoration', 2, 2, 1200, 1),
  ('baseball_stadium', 'Baseball Stadium', 'decoration', 3, 3, 6000, 1),
  ('mini_golf_course', 'Mini Golf', 'decoration', 2, 2, 700, 1),
  ('go_kart_track', 'Go-Kart Track', 'decoration', 2, 2, 1000, 1),
  ('amphitheater', 'Amphitheater', 'decoration', 2, 2, 1500, 1),
  ('greenhouse_garden', 'Greenhouse Garden', 'decoration', 2, 2, 800, 1),
  ('marina_docks_small', 'Marina', 'decoration', 2, 2, 1200, 1),
  ('roller_coaster_small', 'Roller Coaster', 'decoration', 2, 2, 3000, 1),
  ('mountain_lodge', 'Mountain Lodge', 'decoration', 2, 2, 1500, 1),
  ('mountain_trailhead', 'Trailhead', 'decoration', 3, 3, 400, 1),
  ('military_base', 'Military Base', 'service', 3, 3, 8000, 1),
  ('military_barracks', 'Barracks', 'service', 2, 2, 2000, 1)
ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  category = VALUES(category),
  footprint_width = VALUES(footprint_width),
  footprint_height = VALUES(footprint_height),
  build_cost = VALUES(build_cost),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;

UPDATE game_item_details
SET build_time_seconds = 60
WHERE tool = 'water_tower';
